---
- name: apache install
  ansible.builtin.apt:
    name: apache2
    update_cache: true
    state: latest

- name: enable and start apache2
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
